-- ============================================================
-- HIREMATE AI - INITIAL POSTGRESQL 16 TABLES SCHEMA (3NF)
-- Master Specification: PROJECT_MASTER_SPECIFICATION.md
-- ============================================================

-- 1. users
-- 2. skills
-- 3. question_bank
-- 4. candidate_profiles
-- 5. candidate_skills
-- 6. cvs
-- 7. companies
-- 8. jobs
-- 9. job_skills
-- 10. ai_job_matches
-- 11. applications
-- 12. recruitment_pipeline_logs
-- 13. interview_sessions
-- 14. interview_details
-- 15. practice_progress_logs
-- 16. notifications
