/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "rgba(10, 14, 26, 0.65)",
        "on-primary-fixed": "#3d0020",
        "error": "#ff4444",
        "primary-fixed-dim": "#ff80aa",
        "surface-variant": "var(--surface-variant, rgba(54, 20, 64, 0.65))",
        "secondary-fixed": "#c0fff4",
        "background": "transparent",
        "error-container": "#3d0f0f",
        "on-surface-variant": "var(--on-surface-variant, #f2dbe6)",
        "primary-container": "#b3004e",
        "inverse-on-surface": "#0a0a12",
        "secondary-fixed-dim": "#00e6b8",
        "on-primary-fixed-variant": "#8c0038",
        "on-secondary": "#001a1a",
        "surface-container-low": "var(--surface-container-low, rgba(24, 10, 28, 0.62))",
        "tertiary-fixed": "#fff0c0",
        "on-secondary-fixed": "#001a1a",
        "on-secondary-fixed-variant": "#004d4d",
        "tertiary-container": "#665200",
        "primary-fixed": "#ffe0ec",
        "on-surface": "var(--on-surface, #ffffff)",
        "surface-bright": "rgba(48, 18, 56, 0.80)",
        "inverse-primary": "#8c0038",
        "secondary": "var(--theme-secondary, #00ffcc)",
        "on-error": "#1a0000",
        "surface-container-lowest": "var(--surface-container-lowest, rgba(18, 7, 22, 0.62))",
        "on-primary-container": "#ffe0ec",
        "surface-container-highest": "var(--surface-container-highest, rgba(60, 24, 70, 0.80))",
        "primary": "var(--theme-primary, #ff2d78)",
        "on-tertiary-fixed-variant": "#665200",
        "tertiary": "#ffe04a",
        "on-tertiary-fixed": "#1a1000",
        "surface-tint": "var(--theme-primary, #ff2d78)",
        "on-secondary-container": "#c0fff4",
        "on-background": "#ffffff",
        "on-tertiary-container": "#fff0c0",
        "on-error-container": "#ffa0a0",
        "outline": "var(--outline, rgba(255, 117, 151, 0.48))",
        "on-primary": "#1a0010",
        "tertiary-fixed-dim": "#ffe04a",
        "secondary-container": "#004d3d",
        "on-tertiary": "#1a1000",
        "surface-container": "var(--surface-container, rgba(36, 14, 42, 0.68))",
        "surface": "var(--surface, rgba(28, 11, 32, 0.68))",
        "outline-variant": "var(--outline-variant, rgba(255, 117, 151, 0.32))",
        "surface-container-high": "var(--surface-container-high, rgba(48, 18, 56, 0.75))",
        "inverse-surface": "#e8e0f0",
        obsidian: {
          DEFAULT: '#0B0F17',
          light: '#111827',
          dark: '#070A0F',
          card: '#131B2B'
        },
        brand: {
          primary: '#2563EB',
          accent: '#10B981',
          purple: '#8B5CF6'
        },
        playful: {
          cream: '#FFFDF5',
          slate: '#1E293B',
          violet: '#8B5CF6',
          pink: '#F472B6',
          yellow: '#FBBF24',
          mint: '#34D399',
          muted: '#F1F5F9',
          border: '#1E293B',
          card: '#FFFFFF'
        },
        botanical: {
          alabaster: '#F9F8F4',
          forest: '#2D3A31',
          sage: '#8C9A84',
          clay: '#DCCFC2',
          cream: '#F2F0EB',
          stone: '#E6E2DA',
          terracotta: '#C27B66'
        }
      },
      fontFamily: {
        serif: ["Playfair Display", "Georgia", "serif"],
        heading: ["Playfair Display", "Georgia", "serif"],
        display: ["Playfair Display", "Georgia", "serif"],
        headline: ["Playfair Display", "Georgia", "serif"],
        body: ["Source Sans 3", "Plus Jakarta Sans", "Inter", "sans-serif"],
        label: ["Source Sans 3", "sans-serif"]
      },
      boxShadow: {
        'soft': '0 4px 6px -1px rgba(45, 58, 49, 0.05)',
        'soft-md': '0 10px 15px -3px rgba(45, 58, 49, 0.05)',
        'soft-lg': '0 20px 40px -10px rgba(45, 58, 49, 0.05)',
        'soft-xl': '0 25px 50px -12px rgba(45, 58, 49, 0.15)',
        'pop': '4px 4px 0px 0px #1E293B',
        'pop-hover': '6px 6px 0px 0px #1E293B',
        'pop-active': '2px 2px 0px 0px #1E293B',
        'pop-lg': '8px 8px 0px 0px #1E293B',
        'pop-pink': '5px 5px 0px 0px #F472B6',
        'pop-yellow': '5px 5px 0px 0px #FBBF24',
        'pop-violet': '5px 5px 0px 0px #8B5CF6',
        'pop-mint': '5px 5px 0px 0px #34D399',
        'pop-border': '4px 4px 0px 0px #E2E8F0',
      },
      backdropBlur: {
        glass: '20px',
      }
    },
  },
  plugins: [],
}
